# Form implementation generated from reading ui file '.\gui_files\form.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(328, 241)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 20, 231, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_name)
        self.label_surname = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_surname.setObjectName("label_surname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_surname)
        self.label_date = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_date.setObjectName("label_date")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_date)
        self.label_league = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_league.setObjectName("label_league")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_league)
        self.edit_birthday = QtWidgets.QDateEdit(parent=self.formLayoutWidget)
        self.edit_birthday.setObjectName("edit_birthday")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_birthday)
        self.edit_name = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.edit_name.setObjectName("edit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_name)
        self.edit_surname = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.edit_surname.setObjectName("edit_surname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_surname)
        self.edit_league = QtWidgets.QHBoxLayout()
        self.edit_league.setObjectName("edit_league")
        self.radioButton = QtWidgets.QRadioButton(parent=self.formLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.edit_league.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.formLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.edit_league.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.formLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.edit_league.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.formLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.edit_league.addWidget(self.radioButton_4)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_league)
        self.label_weight = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_weight.setObjectName("label_weight")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_weight)
        self.edit_weight = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.edit_weight.setObjectName("edit_weight")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_weight)
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(160, 170, 81, 31))
        self.addButton.setObjectName("addButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Имя"))
        self.label_surname.setText(_translate("MainWindow", "Фамилия"))
        self.label_date.setText(_translate("MainWindow", "Дата рождения"))
        self.label_league.setText(_translate("MainWindow", "Лига"))
        self.radioButton.setText(_translate("MainWindow", "A"))
        self.radioButton_2.setText(_translate("MainWindow", "B"))
        self.radioButton_3.setText(_translate("MainWindow", "C"))
        self.radioButton_4.setText(_translate("MainWindow", "O"))
        self.label_weight.setText(_translate("MainWindow", "Вес ( в кг)"))
        self.addButton.setText(_translate("MainWindow", "Добавить"))
