# Form implementation generated from reading ui file 'gui_files/raw_files/athletes.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 505)
        MainWindow.setStyleSheet("background-color: rgb(31, 36, 46);\n"
"color: white;\n"
"font-size: 13pt\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.but_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_menu.sizePolicy().hasHeightForWidth())
        self.but_menu.setSizePolicy(sizePolicy)
        self.but_menu.setMinimumSize(QtCore.QSize(0, 30))
        self.but_menu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.but_menu.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        self.but_menu.setObjectName("but_menu")
        self.verticalLayout.addWidget(self.but_menu)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.getWeight_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.getWeight_Label.setObjectName("getWeight_Label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.getWeight_Label)
        self.getWeight_Combo = QtWidgets.QComboBox(parent=self.centralwidget)
        self.getWeight_Combo.setMinimumSize(QtCore.QSize(0, 0))
        self.getWeight_Combo.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border-color: rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"")
        self.getWeight_Combo.setObjectName("getWeight_Combo")
        self.getWeight_Combo.addItem("")
        self.getWeight_Combo.setItemText(0, "")
        self.getWeight_Combo.addItem("")
        self.getWeight_Combo.addItem("")
        self.getWeight_Combo.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.getWeight_Combo)
        self.getYear_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.getYear_Label.setObjectName("getYear_Label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.getYear_Label)
        self.getYear_SpinBox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.getYear_SpinBox.setMinimumSize(QtCore.QSize(60, 9))
        self.getYear_SpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.getYear_SpinBox.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.getYear_SpinBox.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border-color: rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"\n"
"")
        self.getYear_SpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.getYear_SpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.getYear_SpinBox.setMinimum(1900)
        self.getYear_SpinBox.setMaximum(2200)
        self.getYear_SpinBox.setProperty("value", 2015)
        self.getYear_SpinBox.setObjectName("getYear_SpinBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.getYear_SpinBox)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.getLeague_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.getLeague_Label.setObjectName("getLeague_Label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.getLeague_Label)
        self.getLeague_ComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.getLeague_ComboBox.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border-color: rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"padding-left: 5px;")
        self.getLeague_ComboBox.setObjectName("getLeague_ComboBox")
        self.getLeague_ComboBox.addItem("")
        self.getLeague_ComboBox.setItemText(0, "")
        self.getLeague_ComboBox.addItem("")
        self.getLeague_ComboBox.addItem("")
        self.getLeague_ComboBox.addItem("")
        self.getLeague_ComboBox.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.getLeague_ComboBox)
        self.getSurname_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.getSurname_Label.setObjectName("getSurname_Label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.getSurname_Label)
        self.getSurname_LineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.getSurname_LineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getSurname_LineEdit.sizePolicy().hasHeightForWidth())
        self.getSurname_LineEdit.setSizePolicy(sizePolicy)
        self.getSurname_LineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.getSurname_LineEdit.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border-color: rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"padding-left: 5px;")
        self.getSurname_LineEdit.setObjectName("getSurname_LineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.getSurname_LineEdit)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.foundButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foundButton.sizePolicy().hasHeightForWidth())
        self.foundButton.setSizePolicy(sizePolicy)
        self.foundButton.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        self.foundButton.setObjectName("foundButton")
        self.horizontalLayout.addWidget(self.foundButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"    background-color: rgba(255, 255, 255, 10);\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"    margin-left: -5px;\n"
"}\n"
"QTableWidget::item{\n"
"    border-right:2px solid rgba(255, 255, 255, 50);\n"
"    border-bottom:2px solid white;\n"
"}\n"
"QHeaderView::section{\n"
"    background-color:rgba(255, 255, 255, 0);\n"
"}")
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.but_menu.setText(_translate("MainWindow", "Меню"))
        self.getWeight_Label.setText(_translate("MainWindow", "Вес:"))
        self.getWeight_Combo.setItemText(1, _translate("MainWindow", "20-40"))
        self.getWeight_Combo.setItemText(2, _translate("MainWindow", "41-60"))
        self.getWeight_Combo.setItemText(3, _translate("MainWindow", "61+"))
        self.getYear_Label.setText(_translate("MainWindow", "Год рождения:"))
        self.getLeague_Label.setText(_translate("MainWindow", "Лига:"))
        self.getLeague_ComboBox.setItemText(1, _translate("MainWindow", "A"))
        self.getLeague_ComboBox.setItemText(2, _translate("MainWindow", "B"))
        self.getLeague_ComboBox.setItemText(3, _translate("MainWindow", "C"))
        self.getLeague_ComboBox.setItemText(4, _translate("MainWindow", "O"))
        self.getSurname_Label.setText(_translate("MainWindow", "Фамилия"))
        self.foundButton.setText(_translate("MainWindow", "Найти"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ФИ"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Вес"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ДР"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Лига"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ЩиСабля"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ЩиМеч"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Траитлон"))
