# Form implementation generated from reading ui file './gui_files/raw_files/addPeople.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 254)
        self.addButton = QtWidgets.QPushButton(parent=Form)
        self.addButton.setGeometry(QtCore.QRect(170, 180, 81, 31))
        self.addButton.setObjectName("addButton")
        self.formLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 231, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_name)
        self.label_surname = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_surname.setObjectName("label_surname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_surname)
        self.label_date = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_date.setObjectName("label_date")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_date)
        self.label_league = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_league.setObjectName("label_league")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_league)
        self.edit_birthday = QtWidgets.QDateEdit(parent=self.formLayoutWidget)
        self.edit_birthday.setObjectName("edit_birthday")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_birthday)
        self.edit_name = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.edit_name.setObjectName("edit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_name)
        self.edit_surname = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.edit_surname.setObjectName("edit_surname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_surname)
        self.edit_league = QtWidgets.QHBoxLayout()
        self.edit_league.setObjectName("edit_league")
        self.radioButton = QtWidgets.QRadioButton(parent=self.formLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.edit_league.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.formLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.edit_league.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.formLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.edit_league.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.formLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.edit_league.addWidget(self.radioButton_4)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_league)
        self.label_weight = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_weight.setObjectName("label_weight")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_weight)
        self.edit_weight = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.edit_weight.setObjectName("edit_weight")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_weight)
        self.but_menu = QtWidgets.QPushButton(parent=Form)
        self.but_menu.setGeometry(QtCore.QRect(10, 220, 71, 31))
        self.but_menu.setObjectName("but_menu")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addButton.setText(_translate("Form", "Добавить"))
        self.label_name.setText(_translate("Form", "Имя"))
        self.label_surname.setText(_translate("Form", "Фамилия"))
        self.label_date.setText(_translate("Form", "Дата рождения"))
        self.label_league.setText(_translate("Form", "Лига"))
        self.radioButton.setText(_translate("Form", "A"))
        self.radioButton_2.setText(_translate("Form", "B"))
        self.radioButton_3.setText(_translate("Form", "C"))
        self.radioButton_4.setText(_translate("Form", "O"))
        self.label_weight.setText(_translate("Form", "Вес ( в кг)"))
        self.but_menu.setText(_translate("Form", "Меню"))
