# Form implementation generated from reading ui file 'gui_files/raw_files/addPeople.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(394, 370)
        Form.setStyleSheet("background-color: rgb(31, 36, 46);\n"
                           "color: white;\n"
                           "font-size: 13pt\n"
                           "")
        self.centralwidget = QtWidgets.QWidget(parent=Form)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.but_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_menu.setMinimumSize(QtCore.QSize(0, 30))
        self.but_menu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.but_menu.setStyleSheet("QPushButton{\n"
                                    "background-color: rgba(255, 255, 255, 30);\n"
                                    "border: 1px solid rgba(255, 255, 255, 40);\n"
                                    "border-radius: 3px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "background-color: rgba(255, 255, 255, 40);\n"
                                    "}\n"
                                    "QPushButton:pressed{\n"
                                    "background-color: rgba(255, 255, 255, 70);\n"
                                    "}")
        self.but_menu.setObjectName("but_menu")
        self.verticalLayout.addWidget(self.but_menu)
        self.Form_2 = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Form_2.sizePolicy().hasHeightForWidth())
        self.Form_2.setSizePolicy(sizePolicy)
        self.Form_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Form_2.setAutoFillBackground(False)
        self.Form_2.setStyleSheet("background-color:None")
        self.Form_2.setObjectName("Form_2")
        self.formLayout = QtWidgets.QFormLayout(self.Form_2)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout.setFormAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(parent=self.Form_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setMinimumSize(QtCore.QSize(0, 0))
        self.label_name.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.label_name.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_name.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_name.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_name.setLineWidth(1)
        self.label_name.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_name)
        self.edit_name = QtWidgets.QLineEdit(parent=self.Form_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_name.sizePolicy().hasHeightForWidth())
        self.edit_name.setSizePolicy(sizePolicy)
        self.edit_name.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_name.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
                                     "border-color: rgba(255, 255, 255, 40);\n"
                                     "border-radius: 3px;\n"
                                     "padding-left: 5px;\n"
                                     "")
        self.edit_name.setObjectName("edit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_name)
        self.label_surname = QtWidgets.QLabel(parent=self.Form_2)
        self.label_surname.setObjectName("label_surname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_surname)
        self.edit_surname = QtWidgets.QLineEdit(parent=self.Form_2)
        self.edit_surname.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_surname.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
                                        "border-color: rgba(255, 255, 255, 40);\n"
                                        "border-radius: 3px;\n"
                                        "padding-left: 5px;\n"
                                        "")
        self.edit_surname.setObjectName("edit_surname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_surname)
        self.edit_birthday = QtWidgets.QDateEdit(parent=self.Form_2)
        self.edit_birthday.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_birthday.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
                                         "border-color: rgba(255, 255, 255, 40);\n"
                                         "border-radius: 3px;\n"
                                         "padding-left: 5px;\n"
                                         "")
        self.edit_birthday.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.edit_birthday.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.edit_birthday.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.edit_birthday.setObjectName("edit_birthday")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_birthday)
        self.label_league = QtWidgets.QLabel(parent=self.Form_2)
        self.label_league.setObjectName("label_league")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_league)
        self.label_weight = QtWidgets.QLabel(parent=self.Form_2)
        self.label_weight.setMinimumSize(QtCore.QSize(0, 0))
        self.label_weight.setObjectName("label_weight")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_weight)
        self.edit_weight = QtWidgets.QLineEdit(parent=self.Form_2)
        self.edit_weight.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_weight.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
                                       "border-color: rgba(255, 255, 255, 40);\n"
                                       "border-radius: 3px;\n"
                                       "padding-left: 5px;\n"
                                       "")
        self.edit_weight.setObjectName("edit_weight")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.edit_weight)
        self.label_date = QtWidgets.QLabel(parent=self.Form_2)
        self.label_date.setObjectName("label_date")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_date)
        self.league = QtWidgets.QFrame(parent=self.Form_2)
        self.league.setMinimumSize(QtCore.QSize(0, 30))
        self.league.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
                                  "border-color: rgba(255, 255, 255, 40);\n"
                                  "border-radius: 3px;\n"
                                  "padding-left: 5px;\n"
                                  "")
        self.league.setObjectName("league")
        self.edit_league = QtWidgets.QHBoxLayout(self.league)
        self.edit_league.setContentsMargins(0, 0, 0, 0)
        self.edit_league.setSpacing(0)
        self.edit_league.setObjectName("edit_league")
        self.league_a = QtWidgets.QRadioButton(parent=self.league)
        self.league_a.setStyleSheet("background-color: None;\n"
                                    "border-color: None;\n"
                                    "")
        self.league_a.setObjectName("league_a")
        self.edit_league.addWidget(self.league_a)
        self.league_b = QtWidgets.QRadioButton(parent=self.league)
        self.league_b.setStyleSheet("background-color: None;\n"
                                    "border-color: None;\n"
                                    "")
        self.league_b.setObjectName("league_b")
        self.edit_league.addWidget(self.league_b)
        self.league_c = QtWidgets.QRadioButton(parent=self.league)
        self.league_c.setStyleSheet("background-color: None;\n"
                                    "border-color: None;\n"
                                    "")
        self.league_c.setObjectName("league_c")
        self.edit_league.addWidget(self.league_c)
        self.league_o = QtWidgets.QRadioButton(parent=self.league)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.league_o.sizePolicy().hasHeightForWidth())
        self.league_o.setSizePolicy(sizePolicy)
        self.league_o.setStyleSheet("background-color: None;\n"
                                    "border-color: None;\n"
                                    "")
        self.league_o.setObjectName("league_o")
        self.edit_league.addWidget(self.league_o)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.league)
        self.verticalLayout.addWidget(self.Form_2)
        self.addButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addButton.setMinimumSize(QtCore.QSize(0, 40))
        self.addButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.addButton.setStyleSheet("QPushButton{\n"
                                     "background-color: rgba(255, 255, 255, 30);\n"
                                     "border: 1px solid rgba(255, 255, 255, 40);\n"
                                     "border-radius: 3px;\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "background-color: rgba(255, 255, 255, 40);\n"
                                     "}\n"
                                     "QPushButton:pressed{\n"
                                     "background-color: rgba(255, 255, 255, 70);\n"
                                     "}")
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton)
        Form.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.but_menu.setText(_translate("Form", "Меню"))
        self.label_name.setText(_translate("Form", "Имя"))
        self.label_surname.setText(_translate("Form", "Фамилия"))
        self.label_league.setText(_translate("Form", "Лига"))
        self.label_weight.setText(_translate("Form", "Вес (через точку)"))
        self.label_date.setText(_translate("Form", "Дата рождения"))
        self.league_a.setText(_translate("Form", "A"))
        self.league_b.setText(_translate("Form", "B"))
        self.league_c.setText(_translate("Form", "C"))
        self.league_o.setText(_translate("Form", "O"))
        self.addButton.setText(_translate("Form", "Добавить"))
