# Form implementation generated from reading ui file './gui_files/raw_files/leagues.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Leagues(object):
    def setupUi(self, Leagues):
        Leagues.setObjectName("Leagues")
        Leagues.resize(623, 441)
        Leagues.setStyleSheet("background-color: rgb(31, 36, 46);\n"
                              "color: white;\n"
                              "font-size: 13pt\n"
                              "")
        self.centralwidget = QtWidgets.QWidget(parent=Leagues)
        self.centralwidget.setObjectName("centralwidget")
        self.but_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_menu.setGeometry(QtCore.QRect(10, 10, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_menu.sizePolicy().hasHeightForWidth())
        self.but_menu.setSizePolicy(sizePolicy)
        self.but_menu.setMinimumSize(QtCore.QSize(0, 30))
        self.but_menu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.but_menu.setStyleSheet("QPushButton{\n"
                                    "background-color: rgba(255, 255, 255, 30);\n"
                                    "border: 1px solid rgba(255, 255, 255, 40);\n"
                                    "border-radius: 3px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "background-color: rgba(255, 255, 255, 40);\n"
                                    "}\n"
                                    "QPushButton:pressed{\n"
                                    "background-color: rgba(255, 255, 255, 70);\n"
                                    "}")
        self.but_menu.setObjectName("but_menu")
        Leagues.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Leagues)
        self.statusbar.setObjectName("statusbar")
        Leagues.setStatusBar(self.statusbar)

        self.retranslateUi(Leagues)
        QtCore.QMetaObject.connectSlotsByName(Leagues)

    def retranslateUi(self, Leagues):
        _translate = QtCore.QCoreApplication.translate
        Leagues.setWindowTitle(_translate("Leagues", "Номинации"))
        self.but_menu.setText(_translate("Leagues", "Меню"))
