# Form implementation generated from reading ui file '.\gui_files\raw_files\nomination_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 271)
        Dialog.setStyleSheet("background-color: rgb(31, 36, 46);\n"
"color: white;\n"
"font-size: 13pt\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(15, 15, 15, 0)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.getWeight_Label = QtWidgets.QLabel(parent=Dialog)
        self.getWeight_Label.setObjectName("getWeight_Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.getWeight_Label)
        self.getWeight_Combo = QtWidgets.QComboBox(parent=Dialog)
        self.getWeight_Combo.setMinimumSize(QtCore.QSize(0, 0))
        self.getWeight_Combo.setStyleSheet("QComboBox{\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border-color: rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"background-color: rgb(38, 46, 61);\n"
"border:1px solid rgba(255, 255, 255, 70);\n"
"border-radius: 3px;\n"
"}\n"
"")
        self.getWeight_Combo.setObjectName("getWeight_Combo")
        self.getWeight_Combo.addItem("")
        self.getWeight_Combo.setItemText(0, "")
        self.getWeight_Combo.addItem("")
        self.getWeight_Combo.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.getWeight_Combo)
        self.getAge_Label = QtWidgets.QLabel(parent=Dialog)
        self.getAge_Label.setObjectName("getAge_Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.getAge_Label)
        self.getAge_Combo = QtWidgets.QComboBox(parent=Dialog)
        self.getAge_Combo.setMinimumSize(QtCore.QSize(0, 0))
        self.getAge_Combo.setStyleSheet("QComboBox{\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border-color: rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"background-color: rgb(38, 46, 61);\n"
"border:1px solid rgba(255, 255, 255, 70);\n"
"border-radius: 3px;\n"
"}\n"
"")
        self.getAge_Combo.setObjectName("getAge_Combo")
        self.getAge_Combo.addItem("")
        self.getAge_Combo.setItemText(0, "")
        self.getAge_Combo.addItem("")
        self.getAge_Combo.addItem("")
        self.getAge_Combo.addItem("")
        self.getAge_Combo.addItem("")
        self.getAge_Combo.addItem("")
        self.getAge_Combo.addItem("")
        self.getAge_Combo.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.getAge_Combo)
        self.getLeague_Label = QtWidgets.QLabel(parent=Dialog)
        self.getLeague_Label.setObjectName("getLeague_Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.getLeague_Label)
        self.getLeague_ComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.getLeague_ComboBox.setStyleSheet("QComboBox{\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border-color: rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"background-color: rgb(38, 46, 61);\n"
"border:1px solid rgba(255, 255, 255, 70);\n"
"border-radius: 3px;\n"
"}\n"
"")
        self.getLeague_ComboBox.setObjectName("getLeague_ComboBox")
        self.getLeague_ComboBox.addItem("")
        self.getLeague_ComboBox.setItemText(0, "")
        self.getLeague_ComboBox.addItem("")
        self.getLeague_ComboBox.addItem("")
        self.getLeague_ComboBox.addItem("")
        self.getLeague_ComboBox.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.getLeague_ComboBox)
        self.getNomination_Label = QtWidgets.QLabel(parent=Dialog)
        self.getNomination_Label.setObjectName("getNomination_Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.getNomination_Label)
        self.getNomination_ComboBox = QtWidgets.QComboBox(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getNomination_ComboBox.sizePolicy().hasHeightForWidth())
        self.getNomination_ComboBox.setSizePolicy(sizePolicy)
        self.getNomination_ComboBox.setStyleSheet("QComboBox{\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border-color: rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"}\n"
"QComboBox QAbstractItemView{\n"
"background-color: rgb(38, 46, 61);\n"
"border:1px solid rgba(255, 255, 255, 70);\n"
"border-radius: 3px;\n"
"}\n"
"")
        self.getNomination_ComboBox.setObjectName("getNomination_ComboBox")
        self.getNomination_ComboBox.addItem("")
        self.getNomination_ComboBox.setItemText(0, "")
        self.getNomination_ComboBox.addItem("")
        self.getNomination_ComboBox.addItem("")
        self.getNomination_ComboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.getNomination_ComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 20, -1, 15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_button = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_button.sizePolicy().hasHeightForWidth())
        self.create_button.setSizePolicy(sizePolicy)
        self.create_button.setMaximumSize(QtCore.QSize(200, 40))
        self.create_button.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        self.create_button.setObjectName("create_button")
        self.horizontalLayout.addWidget(self.create_button)
        self.cancel_button = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setMaximumSize(QtCore.QSize(100, 40))
        self.cancel_button.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.getWeight_Label.setText(_translate("Dialog", "Вес:"))
        self.getWeight_Combo.setItemText(1, _translate("Dialog", "Лёгкий"))
        self.getWeight_Combo.setItemText(2, _translate("Dialog", "Тяжёлый"))
        self.getAge_Label.setText(_translate("Dialog", "Лет:"))
        self.getAge_Combo.setItemText(1, _translate("Dialog", "6-7"))
        self.getAge_Combo.setItemText(2, _translate("Dialog", "8-9"))
        self.getAge_Combo.setItemText(3, _translate("Dialog", "10-11"))
        self.getAge_Combo.setItemText(4, _translate("Dialog", "12-13"))
        self.getAge_Combo.setItemText(5, _translate("Dialog", "14-15"))
        self.getAge_Combo.setItemText(6, _translate("Dialog", "16-17"))
        self.getAge_Combo.setItemText(7, _translate("Dialog", "18-40"))
        self.getLeague_Label.setText(_translate("Dialog", "Лига:"))
        self.getLeague_ComboBox.setItemText(1, _translate("Dialog", "A"))
        self.getLeague_ComboBox.setItemText(2, _translate("Dialog", "B"))
        self.getLeague_ComboBox.setItemText(3, _translate("Dialog", "C"))
        self.getLeague_ComboBox.setItemText(4, _translate("Dialog", "O"))
        self.getNomination_Label.setText(_translate("Dialog", "Номинация:"))
        self.getNomination_ComboBox.setItemText(1, _translate("Dialog", "Меч+щит"))
        self.getNomination_ComboBox.setItemText(2, _translate("Dialog", "Сабля+щит"))
        self.getNomination_ComboBox.setItemText(3, _translate("Dialog", "Триатлон"))
        self.create_button.setText(_translate("Dialog", "Создать Номинацию"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))
