# Form implementation generated from reading ui file 'gui_files/raw_files/settings.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        MainWindow.setStyleSheet("background-color: rgb(31, 36, 46);\n"
"color: white;\n"
"font-size: 12pt\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.but_menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_menu.setGeometry(QtCore.QRect(9, 9, 91, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_menu.sizePolicy().hasHeightForWidth())
        self.but_menu.setSizePolicy(sizePolicy)
        self.but_menu.setMinimumSize(QtCore.QSize(0, 30))
        self.but_menu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.but_menu.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        self.but_menu.setObjectName("but_menu")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 132, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.clear_database = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_database.setGeometry(QtCore.QRect(200, 100, 181, 41))
        self.clear_database.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        self.clear_database.setObjectName("clear_database")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 70, 154, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 131, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 120, 41, 21))
        self.lineEdit.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border-color: rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"padding-left: 5px;")
        self.lineEdit.setObjectName("lineEdit")
        self.save_database_txt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_database_txt.setGeometry(QtCore.QRect(150, 150, 231, 41))
        self.save_database_txt.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        self.save_database_txt.setObjectName("save_database_txt")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.but_menu.setText(_translate("MainWindow", "Меню"))
        self.label_2.setText(_translate("MainWindow", "Общие настройки"))
        self.clear_database.setText(_translate("MainWindow", "Отчистить базу данных"))
        self.label.setText(_translate("MainWindow", "Настройки бд"))
        self.label_3.setText(_translate("MainWindow", "Критический вес:"))
        self.save_database_txt.setText(_translate("MainWindow", "Сохранить базу в формате txt"))
